export const PATTERN = {
  AUTH: {
    LOGIN: { cmd: 'login' },
    REGISTER: { cmd: 'register' },
    REFRESH_TOKEN: { cmd: 'refresh_token' },
  },
  USER: {
    GET_PROFILE: { cmd: 'get_profile' },
    CREATE_USER: { cmd: 'create_user' },
    TOGGLE_BLOCK: { cmd: 'toggle_block' },
    SEARCH_USERS: { cmd: 'search_users' },
    FIND_BY_EMAIL: { cmd: 'find_by_email' },
    GET_BLOCK_LIST: { cmd: 'get_block_list' },
    UPDATE_PROFILE: { cmd: 'update_profile' },
    GET_REFRESH_TOKEN: { cmd: 'get_refresh_token' },
    UPDATE_REFRESH_TOKEN: { cmd: 'update_refresh_token' },

    GET_FRIENDS: { cmd: 'get_friends' },
    SEND_REQUEST: { cmd: 'send_request' },
    ACCEPT_REQUEST: { cmd: 'accept_request' },
    REJECT_REQUEST: { cmd: 'reject_request' },
    CHECK_IS_FRIENDS: { cmd: 'check_is_friends' },
    GET_INCOMING_REQUESTS: { cmd: 'get_incoming_requests' },
  },
  CHAT: {
    CHECK_IS_MEMBER: { cmd: 'check_is_member' },
    GET_CONVERSATION: { cmd: 'get_conversation' },
    UPDATE_LAST_MESSAGE: { cmd: 'update_last_message' },
    CREATE_CONVERSATION: { cmd: 'create_conversation' },
    GET_ALL_CONVERSATIONS: { cmd: 'get_all_conversations' },
    CHECK_CONVERSATION_EXISTS: { cmd: 'check_conversation_exists' },

    EDIT_MESSAGE: { cmd: 'edit_message' },
    DELETE_MESSAGE: { cmd: 'delete_message' },
    CREATE_MESSAGE: { cmd: 'create_message' },
    GET_ALL_MESSAGES: { cmd: 'get_all_messages' },
    GET_MESSAGE: { cmd: 'get_message' },
    NEW_MESSAGE: { cmd: 'new_message' },

    GET_MEMBERS: { cmd: 'get_members' },
    ADD_MEMBERS: { cmd: 'add_members' },
    REMOVE_MEMBER: { cmd: 'remove_member' },
    GET_MEMBER_ROLE: { cmd: 'get_member_role' },
    CHANGE_MEMBER_ROLE: { cmd: 'change_member_role' },
  },
  NOTIFICATION: {
    CREATE_NEW_NOTIFICATION: { cmd: 'create_new_notification' },
    NOTIFY_USER: { cmd: 'notify_user' },
  },
};
